spring:
  datasource:
    local:
      url: jdbc:postgresql://localhost:5432/db?currentSchema=budget
      user: user
      password: password
    docker:
      url: jdbc:postgresql://db:5432/db?currentSchema=budget
      user: user
      password: password